@Yape.Transaction.API_HostAddress = http://localhost:5113

### Get all transactions
GET {{Yape.Transaction.API_HostAddress}}/api/Transactions
Accept: application/json

###

### Get a transaction by ID
GET {{Yape.Transaction.API_HostAddress}}/api/Transactions/GetByExternalId/{{transactionId}}
Accept: application/json

###

### Create a new transaction
POST {{Yape.Transaction.API_HostAddress}}/api/Transactions
Content-Type: application/json

{
  "sourceAccountId": "c323a7c9-9df9-4588-ae24-80fa603cfd75",
  "destinationAccountId": "ea7abc43-9efd-40a8-ac85-07c368032ff4",
  "transferTypeId": 1,
  "value": 1000
}

###

