<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Yape.AntiFraud.Worker-65c9a911-8560-4dc7-a671-d97519df66d4</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.10.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Yape.Domain\Yape.Domain.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Yape.Infrastructure.AntiFraudApi\Yape.Infrastructure.AntiFraudApi.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Yape.Infrastructure.Kafka\Yape.Infrastructure.Kafka.csproj" />
  </ItemGroup>
</Project>
