<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>227c7a25-ba18-48e9-bb2e-fa7f3232b4cc</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.14" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\Yape.Application.Antifraud\Yape.Application.Antifraud.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Yape.Infrastructure.Kafka\Yape.Infrastructure.Kafka.csproj" />
    <ProjectReference Include="..\..\Infrastructure\Yape.Infrastructure.Postgresql\Yape.Infrastructure.Postgresql.csproj" />
  </ItemGroup>

</Project>
